// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "user-profile": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microservice-user-profile/design
// --out=$(GOPATH)/src/github.com/Microkubes/microservice-user-profile
// --version=v1.3.0

package app
