// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "user-profile": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-user-profile/design
// --out=$(GOPATH)src/github.com/JormungandrK/microservice-user-profile
// --version=v1.2.0-dirty

package test
