// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "user-profile": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microservice-user-profile/design
// --out=$(GOPATH)/src/github.com/Microkubes/microservice-user-profile
// --version=v1.3.1

package test
