// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "user-profile": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-user-profile/design
// --out=$(GOPATH)/src/github.com/JormungandrK/microservice-user-profile
// --version=v1.3.0

package test
